---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-creator-sa
  namespace: hiro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-creator-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-creator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: pod-creator-sa
  namespace: hiro
roleRef:
  kind: ClusterRole
  name: pod-creator-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-steal-worker
  namespace: hiro
  labels:
    app: workload-steal-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-steal-worker
  template:
    metadata:
      labels:
        app: workload-steal-worker
    spec:
      serviceAccountName: pod-creator-sa
      containers:
        - name: workload-steal-worker
          image: workloadstealworker:alpha1
          imagePullPolicy: IfNotPresent
          env:
          - name: NATS_URL
            value: "demo.nats.io:4222"  
          - name: NATS_SUBJECT
            value: "WorkStealingPod"  
          - name: WORK_LOAD_STEAL_LABLE
            value: "WorkLoadSteal"  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          
          